backend:
  build: .
  environment:
      RAILS_ENV: development
  command: bundle exec rails s"
  volumes:
    - /app
  ports:
    - "3000:3000"

nginx:
  restart: always
  build: ./docker/nginx/
  ports:
    - "80:80"
  links:
    - backend
